version: '4'
services:
  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - backend
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - mongodb_uri:value
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: king
      MONGO_INITDB_ROOT_PASSWORD: king
