version: '4'
services:
  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - backend
    networks:
      yolo-test-network:
        ipv4_address: 172.60.0.2
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      mongodb_uri: 'mongodb://king:king@172.60.0.4:27017'
    depends_on:
      - database
    networks:
      yolo-test-network:
        ipv4_address: 172.60.0.3
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: king
      MONGO_INITDB_ROOT_PASSWORD: king
    ports:
      - 27017:27017
    networks:
      yolo-test-network:
        ipv4_address: 172.60.0.4


networks:
  yolo-test-network:
    ipam:
      driver: default
      config:
        - subnet: 172.60.0.0/16